destination: ./_site
lsi:         false
port: 4000
pygments:    true
markdown:    maruku
permalink:   /:year/:month/:day/:title
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
exclude: [design, scripts, README.md]

tag_title_prefix: "TechTinkering Articles Tagged With: "
